import{a as E,S as B,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const R="50678638-8abf3cfccb9b2132419321a6d",$="https://pixabay.com/api/",M=15;async function m(o,t=1){const n={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:t};return(await E.get($,{params:n})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),P=new B(".gallery a");function g(o){const t=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:i,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img src="${n}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${w}</p>
        <p><b>Downloads:</b> ${S}</p>
      </div>
    </li>`).join("");p.insertAdjacentHTML("beforeend",t),P.refresh()}function O(){p.innerHTML=""}function b(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function q(){y.classList.remove("hidden")}function v(){y.classList.add("hidden")}const f=document.querySelector(".form"),x=document.querySelector(".load-more");let l="",d=1,u=0,c=0;f.addEventListener("submit",async o=>{if(o.preventDefault(),l=f.querySelector('input[name="search-text"]').value.trim(),!l){a.warning({message:"Enter a search query!",position:"topRight"});return}d=1,c=0,O(),v(),b();try{const t=await m(l,d);if(u=t.totalHits,t.hits.length===0){a.info({message:"No images found. Try another query.",position:"topRight"});return}g(t.hits),c+=t.hits.length,c<u&&q()}catch(t){console.error(t),a.error({message:"Error loading images.",position:"topRight"})}finally{L()}});x.addEventListener("click",async()=>{d+=1,v(),b();try{const o=await m(l,d);g(o.hits),c+=o.hits.length,A(),c>=u?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):q()}catch(o){console.error(o),a.error({message:"Unable to load more.",position:"topRight"})}finally{L()}});function A(){const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
